import Footer from "../components/Footer";
import Header from "../components/Header";
import "../styles/global.css";

export const metadata = {
  title: "CPU onboarding",
  description: "Generated by create next app",
};

export default function RootLayout({ children, locale }) {
  return (
    /* it was and showing: Ensure the lang attribute of the <html> element has a valid value
        <html lang={{ locale }}>
        Now updated line 16
    */
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header locale={locale} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
